initscript: Rewrite stop command
 o Return correct error codes
 o Be more generous with signal timeouts

diff --git a/debian/nginx-common.nginx.init b/debian/nginx-common.nginx.init
--- a/debian/nginx-common.nginx.init
+++ b/debian/nginx-common.nginx.init
@@ -64,9 +64,21 @@ test_nginx_config() {
 	fi
 }
 
-stop() {
-	start-stop-daemon --stop --quiet --pidfile $PID \
-		--retry 5 --oknodo --exec $DAEMON
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PID --name $NAME
+	RETVAL="$?"
+
+	sleep 1
+	return "$RETVAL"
 }
 
 case "$1" in
@@ -79,11 +91,13 @@ case "$1" in
 		esac
 		;;
 	stop)
-		stop
-		log_daemon_msg "Stopping $DESC" "$NAME"
-		log_end_msg $?
+		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+		do_stop
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
 		;;
-
 	restart|force-reload)
 		log_daemon_msg "Restarting $DESC" "$NAME"
 		test_nginx_config
